[2023-06-15T06:19:14.684+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T06:19:02.642551+00:00 [queued]>
[2023-06-15T06:19:14.710+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T06:19:02.642551+00:00 [queued]>
[2023-06-15T06:19:14.712+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T06:19:14.714+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T06:19:14.715+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T06:19:14.756+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 06:19:02.642551+00:00
[2023-06-15T06:19:14.779+0000] {standard_task_runner.py:55} INFO - Started process 2333 to run task
[2023-06-15T06:19:14.824+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T06:19:02.642551+00:00', '--job-id', '314', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_kaggle2.py', '--cfg-path', '/tmp/tmphbb7te8b']
[2023-06-15T06:19:14.825+0000] {standard_task_runner.py:83} INFO - Job 314: Subtask download_dataset_task
[2023-06-15T06:19:15.134+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T06:19:02.642551+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T06:19:15.402+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T06:19:02.642551+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T06:19:02.642551+00:00
[2023-06-15T06:19:15.478+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T06:19:15.510+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d sherrytp/airline-delay-analysis -p /opt/***/airline-delay-analysis && unzip /opt/***/airline-delay-analysis/airline-delay-analysis.zip -d /opt/***/airline-delay-analysis']
[2023-06-15T06:19:15.632+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T06:19:17.604+0000] {subprocess.py:93} INFO - airline-delay-analysis.zip: Skipping, found more recently modified local copy (use --force to force download)
[2023-06-15T06:19:17.844+0000] {subprocess.py:93} INFO - Archive:  /opt/***/airline-delay-analysis/airline-delay-analysis.zip
[2023-06-15T06:19:17.855+0000] {subprocess.py:93} INFO - replace /opt/***/airline-delay-analysis/airline delay analysis/20.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
[2023-06-15T06:19:17.858+0000] {subprocess.py:93} INFO - (EOF or read error, treating as "[N]one" ...)
[2023-06-15T06:19:17.890+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-15T06:19:17.908+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-15T06:19:17.917+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T061902, start_date=20230615T061914, end_date=20230615T061917
[2023-06-15T06:19:17.959+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 314 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 2333)
[2023-06-15T06:19:18.023+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T06:19:18.097+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
