[2023-06-14T23:32:06.162+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2023-06-14T23:23:58.132945+00:00 [queued]>
[2023-06-14T23:32:06.184+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2023-06-14T23:23:58.132945+00:00 [queued]>
[2023-06-14T23:32:06.185+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T23:32:06.186+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-06-14T23:32:06.187+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T23:32:06.212+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2023-06-14 23:23:58.132945+00:00
[2023-06-14T23:32:06.230+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task', 'manual__2023-06-14T23:23:58.132945+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp9zbu0hv9']
[2023-06-14T23:32:06.226+0000] {standard_task_runner.py:55} INFO - Started process 3895 to run task
[2023-06-14T23:32:06.232+0000] {standard_task_runner.py:83} INFO - Job 206: Subtask format_to_parquet_task
[2023-06-14T23:32:06.660+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2023-06-14T23:23:58.132945+00:00 [running]> on host 570ce802d94a
[2023-06-14T23:32:06.836+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-14T23:23:58.132945+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-14T23:23:58.132945+00:00
[2023-06-14T23:33:51.807+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 41, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 1212, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1077, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1694, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1665, in pyarrow.lib.get_native_file
  File "pyarrow/io.pxi", line 943, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 953, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 113, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file '/opt/airflow/airline-delay-analysis/airline-delay-analysis.csv'. Detail: [errno 2] No such file or directory
[2023-06-14T23:33:52.197+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=format_to_parquet_task, execution_date=20230614T232358, start_date=20230614T233206, end_date=20230614T233352
[2023-06-14T23:33:52.523+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 206 for task format_to_parquet_task ([Errno 2] Failed to open local file '/opt/airflow/airline-delay-analysis/airline-delay-analysis.csv'. Detail: [errno 2] No such file or directory; 3895)
[2023-06-14T23:33:52.633+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-14T23:33:52.953+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
