[2023-06-15T13:03:07.780+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T13:02:45.795635+00:00 [queued]>
[2023-06-15T13:03:07.798+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T13:02:45.795635+00:00 [queued]>
[2023-06-15T13:03:07.799+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T13:03:07.800+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T13:03:07.800+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T13:03:07.830+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 13:02:45.795635+00:00
[2023-06-15T13:03:07.842+0000] {standard_task_runner.py:55} INFO - Started process 20915 to run task
[2023-06-15T13:03:07.883+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T13:02:45.795635+00:00', '--job-id', '419', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpprv9r3i9']
[2023-06-15T13:03:07.886+0000] {standard_task_runner.py:83} INFO - Job 419: Subtask download_dataset_task
[2023-06-15T13:03:08.035+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T13:02:45.795635+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T13:03:08.177+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T13:02:45.795635+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T13:02:45.795635+00:00
[2023-06-15T13:03:08.179+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T13:03:08.182+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/*** && rm * && kaggle datasets download -d arnabchaki/data-science-salaries-2023 --force && unzip data-science-salaries-2023.zip && rm data-science-salaries-2023.zip\n            ']
[2023-06-15T13:03:08.212+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T13:03:08.267+0000] {subprocess.py:93} INFO - rm: cannot remove 'airline-delay-analysis': Is a directory
[2023-06-15T13:03:08.268+0000] {subprocess.py:93} INFO - rm: cannot remove 'dags': Is a directory
[2023-06-15T13:03:08.295+0000] {subprocess.py:93} INFO - rm: cannot remove 'datasets': Is a directory
[2023-06-15T13:03:08.300+0000] {subprocess.py:93} INFO - rm: cannot remove 'logs': Is a directory
[2023-06-15T13:03:08.301+0000] {subprocess.py:93} INFO - rm: cannot remove 'plugins': Is a directory
[2023-06-15T13:03:08.309+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-15T13:03:08.329+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-15T13:03:08.346+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T130245, start_date=20230615T130307, end_date=20230615T130308
[2023-06-15T13:03:08.371+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 419 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 20915)
[2023-06-15T13:03:08.420+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T13:03:08.491+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
