[2023-06-15T17:53:00.627+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T17:52:44.494905+00:00 [queued]>
[2023-06-15T17:53:00.670+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T17:52:44.494905+00:00 [queued]>
[2023-06-15T17:53:00.672+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T17:53:00.674+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T17:53:00.676+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T17:53:00.711+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 17:52:44.494905+00:00
[2023-06-15T17:53:00.735+0000] {standard_task_runner.py:55} INFO - Started process 1869 to run task
[2023-06-15T17:53:00.739+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T17:52:44.494905+00:00', '--job-id', '468', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpirbkgud_']
[2023-06-15T17:53:00.742+0000] {standard_task_runner.py:83} INFO - Job 468: Subtask download_dataset_task
[2023-06-15T17:53:00.898+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T17:52:44.494905+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T17:53:01.105+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T17:52:44.494905+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T17:52:44.494905+00:00
[2023-06-15T17:53:01.132+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T17:53:01.200+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        cd /opt/*** &&\n        if [ ! -d direct-messaging ]; then\n            mkdir direct-messaging &&\n            cd direct-messaging &&\n            kaggle datasets download -d mkechinov/direct-messaging --force &&\n            unzip direct-messaging.zip && \n            rm direct-messaging.zip\n            ls\n        fi &&\n        ']
[2023-06-15T17:53:01.258+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T17:53:01.297+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 12: syntax error: unexpected end of file
[2023-06-15T17:53:01.298+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-15T17:53:01.323+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-15T17:53:01.335+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T175244, start_date=20230615T175300, end_date=20230615T175301
[2023-06-15T17:53:01.408+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 468 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 2.; 1869)
[2023-06-15T17:53:01.476+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T17:53:01.530+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
