[2023-06-14T23:17:11.522+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-14T23:11:52.569878+00:00 [queued]>
[2023-06-14T23:17:11.542+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-14T23:11:52.569878+00:00 [queued]>
[2023-06-14T23:17:11.543+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T23:17:11.544+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-06-14T23:17:11.545+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T23:17:11.572+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-14 23:11:52.569878+00:00
[2023-06-14T23:17:11.728+0000] {standard_task_runner.py:55} INFO - Started process 3003 to run task
[2023-06-14T23:17:11.737+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-14T23:11:52.569878+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpk0e8mxe2']
[2023-06-14T23:17:11.738+0000] {standard_task_runner.py:83} INFO - Job 201: Subtask download_dataset_task
[2023-06-14T23:17:11.855+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-14T23:11:52.569878+00:00 [running]> on host 570ce802d94a
[2023-06-14T23:17:12.023+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-14T23:11:52.569878+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-14T23:11:52.569878+00:00
[2023-06-14T23:17:12.026+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-14T23:17:12.037+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d sherrytp/airline-delay-analysis -p /opt/***/airline-delay-analysis && unzip /opt/***/airline-delay-analysis/airline-delay-analysis.zip -d /opt/***/airline-delay-analysis']
[2023-06-14T23:17:12.077+0000] {subprocess.py:86} INFO - Output:
[2023-06-14T23:17:13.739+0000] {subprocess.py:93} INFO - airline-delay-analysis.zip: Skipping, found more recently modified local copy (use --force to force download)
[2023-06-14T23:17:13.943+0000] {subprocess.py:93} INFO - Archive:  /opt/***/airline-delay-analysis/airline-delay-analysis.zip
[2023-06-14T23:17:13.945+0000] {subprocess.py:93} INFO - replace /opt/***/airline-delay-analysis/airline delay analysis/20.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
[2023-06-14T23:17:13.946+0000] {subprocess.py:93} INFO - (EOF or read error, treating as "[N]one" ...)
[2023-06-14T23:17:13.952+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-14T23:17:13.966+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-14T23:17:13.971+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230614T231152, start_date=20230614T231711, end_date=20230614T231713
[2023-06-14T23:17:13.995+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 201 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 3003)
[2023-06-14T23:17:14.040+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-14T23:17:14.079+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
