[2023-06-15T03:56:08.581+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T03:50:48.427474+00:00 [queued]>
[2023-06-15T03:56:08.597+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T03:50:48.427474+00:00 [queued]>
[2023-06-15T03:56:08.598+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T03:56:08.599+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-06-15T03:56:08.600+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T03:56:08.625+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 03:50:48.427474+00:00
[2023-06-15T03:56:08.638+0000] {standard_task_runner.py:55} INFO - Started process 2789 to run task
[2023-06-15T03:56:08.641+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T03:50:48.427474+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_kaggle.py', '--cfg-path', '/tmp/tmphu5q2u81']
[2023-06-15T03:56:08.643+0000] {standard_task_runner.py:83} INFO - Job 275: Subtask download_dataset_task
[2023-06-15T03:56:08.730+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T03:50:48.427474+00:00 [running]> on host 7e4a92a12ba6
[2023-06-15T03:56:08.833+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T03:50:48.427474+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T03:50:48.427474+00:00
[2023-06-15T03:56:08.836+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T03:56:08.846+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d sherrytp/airline-delay-analysis -p /opt/***/airline-delay-analysis && unzip /opt/***/airline-delay-analysis/airline-delay-analysis.zip -d /opt/***/airline-delay-analysis']
[2023-06-15T03:56:08.870+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T03:56:10.357+0000] {subprocess.py:93} INFO - airline-delay-analysis.zip: Skipping, found more recently modified local copy (use --force to force download)
[2023-06-15T03:56:10.534+0000] {subprocess.py:93} INFO - Archive:  /opt/***/airline-delay-analysis/airline-delay-analysis.zip
[2023-06-15T03:56:10.536+0000] {subprocess.py:93} INFO - replace /opt/***/airline-delay-analysis/airline delay analysis/20.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
[2023-06-15T03:56:10.538+0000] {subprocess.py:93} INFO - (EOF or read error, treating as "[N]one" ...)
[2023-06-15T03:56:10.549+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-15T03:56:10.567+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-15T03:56:10.574+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T035048, start_date=20230615T035608, end_date=20230615T035610
[2023-06-15T03:56:10.601+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 275 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 2789)
[2023-06-15T03:56:10.664+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T03:56:10.711+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
