[2023-06-15T12:51:00.041+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T12:50:01.570886+00:00 [queued]>
[2023-06-15T12:51:00.069+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T12:50:01.570886+00:00 [queued]>
[2023-06-15T12:51:00.070+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T12:51:00.071+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T12:51:00.072+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T12:51:00.147+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 12:50:01.570886+00:00
[2023-06-15T12:51:00.171+0000] {standard_task_runner.py:55} INFO - Started process 20164 to run task
[2023-06-15T12:51:00.175+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T12:50:01.570886+00:00', '--job-id', '412', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpwqkmc4ji']
[2023-06-15T12:51:00.182+0000] {standard_task_runner.py:83} INFO - Job 412: Subtask download_dataset_task
[2023-06-15T12:51:00.369+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T12:50:01.570886+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T12:51:00.503+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T12:50:01.570886+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T12:50:01.570886+00:00
[2023-06-15T12:51:00.506+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T12:51:00.512+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            rm data-science-salaries-2023 &&\n            mkdir -p /opt/***/data-science-salaries-2023 &&\n            cd /opt/*** && kaggle datasets download -d arnabchaki/data-science-salaries-2023 && unzip data-science-salaries-2023.zip && rm data-science-salaries-2023.zip']
[2023-06-15T12:51:00.544+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T12:51:00.564+0000] {subprocess.py:93} INFO - rm: cannot remove 'data-science-salaries-2023': No such file or directory
[2023-06-15T12:51:00.565+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-15T12:51:00.592+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-15T12:51:00.602+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T125001, start_date=20230615T125100, end_date=20230615T125100
[2023-06-15T12:51:00.632+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 412 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 20164)
[2023-06-15T12:51:00.673+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T12:51:00.742+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
