[2023-06-15T05:08:08.729+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T05:07:54.120109+00:00 [queued]>
[2023-06-15T05:08:08.807+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T05:07:54.120109+00:00 [queued]>
[2023-06-15T05:08:08.809+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T05:08:08.813+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T05:08:08.817+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T05:08:08.877+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 05:07:54.120109+00:00
[2023-06-15T05:08:08.918+0000] {standard_task_runner.py:55} INFO - Started process 6638 to run task
[2023-06-15T05:08:08.930+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T05:07:54.120109+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp1a_xcd6c']
[2023-06-15T05:08:08.936+0000] {standard_task_runner.py:83} INFO - Job 295: Subtask download_dataset_task
[2023-06-15T05:08:09.130+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T05:07:54.120109+00:00 [running]> on host 7e4a92a12ba6
[2023-06-15T05:08:09.325+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T05:07:54.120109+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T05:07:54.120109+00:00
[2023-06-15T05:08:09.330+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T05:08:09.340+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSL kaggle datasets download -d sherrytp/airline-delay-analysis > /opt/***/airline-delay-analysis.csv']
[2023-06-15T05:08:09.376+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T05:08:19.469+0000] {subprocess.py:93} INFO - curl: (6) Could not resolve host: kaggle
[2023-06-15T05:08:29.476+0000] {subprocess.py:93} INFO - curl: (6) Could not resolve host: datasets
[2023-06-15T05:08:39.495+0000] {subprocess.py:93} INFO - curl: (6) Could not resolve host: download
[2023-06-15T05:08:39.499+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2023-06-15T05:08:39.535+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2023-06-15T05:08:39.549+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T050754, start_date=20230615T050808, end_date=20230615T050839
[2023-06-15T05:08:39.609+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 295 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 6.; 6638)
[2023-06-15T05:08:39.662+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T05:08:39.807+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
