[2023-06-15T12:18:15.547+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T12:12:51.873032+00:00 [queued]>
[2023-06-15T12:18:15.562+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T12:12:51.873032+00:00 [queued]>
[2023-06-15T12:18:15.563+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T12:18:15.564+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-06-15T12:18:15.565+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T12:18:15.590+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 12:12:51.873032+00:00
[2023-06-15T12:18:15.602+0000] {standard_task_runner.py:55} INFO - Started process 18331 to run task
[2023-06-15T12:18:15.606+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T12:12:51.873032+00:00', '--job-id', '410', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmprb6kj9mn']
[2023-06-15T12:18:15.609+0000] {standard_task_runner.py:83} INFO - Job 410: Subtask download_dataset_task
[2023-06-15T12:18:15.714+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T12:12:51.873032+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T12:18:15.816+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T12:12:51.873032+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T12:12:51.873032+00:00
[2023-06-15T12:18:15.820+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T12:18:15.824+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            mkdir -p /opt/***/data-science-salaries-2023 &&\n            cd /opt/*** && kaggle datasets download -d arnabchaki/data-science-salaries-2023 && unzip data-science-salaries-2023.zip && rm data-science-salaries-2023.zip']
[2023-06-15T12:18:15.851+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T12:18:15.871+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/***/data-science-salaries-2023’: File exists
[2023-06-15T12:18:15.873+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-15T12:18:15.889+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-15T12:18:15.897+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T121251, start_date=20230615T121815, end_date=20230615T121815
[2023-06-15T12:18:15.923+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 410 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 18331)
[2023-06-15T12:18:15.941+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T12:18:15.980+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
