[2023-06-15T18:03:51.497+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T18:03:42.154983+00:00 [queued]>
[2023-06-15T18:03:51.511+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T18:03:42.154983+00:00 [queued]>
[2023-06-15T18:03:51.512+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T18:03:51.513+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-15T18:03:51.514+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-15T18:03:51.541+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-15 18:03:42.154983+00:00
[2023-06-15T18:03:51.555+0000] {standard_task_runner.py:55} INFO - Started process 2449 to run task
[2023-06-15T18:03:51.560+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'manual__2023-06-15T18:03:42.154983+00:00', '--job-id', '474', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpvha_w61c']
[2023-06-15T18:03:51.563+0000] {standard_task_runner.py:83} INFO - Job 474: Subtask download_dataset_task
[2023-06-15T18:03:51.659+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task manual__2023-06-15T18:03:42.154983+00:00 [running]> on host 658b05ff6f1a
[2023-06-15T18:03:51.765+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-15T18:03:42.154983+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-15T18:03:42.154983+00:00
[2023-06-15T18:03:51.768+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-15T18:03:51.772+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        cd /opt/*** &&\n        if [ ! -d direct-messaging ]; then\n            mkdir direct-messaging &&\n            cd direct-messaging &&\n            kaggle datasets download -d mkechinov/direct-messaging --force &&\n            unzip direct-messaging.zip && \n            rm direct-messaging.zip &&\n        fi &&\n        cd direct-messaging &&\n        ls \n        ']
[2023-06-15T18:03:51.793+0000] {subprocess.py:86} INFO - Output:
[2023-06-15T18:03:51.796+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 9: syntax error near unexpected token `fi'
[2023-06-15T18:03:51.797+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 9: `        fi &&'
[2023-06-15T18:03:51.798+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-06-15T18:03:51.812+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-06-15T18:03:51.818+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230615T180342, start_date=20230615T180351, end_date=20230615T180351
[2023-06-15T18:03:51.839+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 474 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 2.; 2449)
[2023-06-15T18:03:51.852+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-15T18:03:51.895+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
